### ISSUE TITLE
CurTime

### ISSUE THREAD

**Issue by Mijyuoon** [MysteryPancake/GitHub-Rule-Book#1]
> CurTime must be used, not RealTime or SysTime.

Uhhhhh, that's stupid. All those have different use cases. You should use `RealTime` instead of `CurTime` for UI animations, for example. And `SysTime` is used for precise time measurement when doing stuff like benchmarking or similar. In those cases using `CurTime` instead is both stupid and wrong.

**Comment by Kefta** [comment]
I wouldn't say it's "stupid" to use CurTime -- in fact, if I recall correctly, the engine originally used gpGlobals->curtime for UI timing before using an unscaled delta. Just better to use RealTime for unpredicted timers/effects.

**Comment by MysteryPancake** [comment]
I find the wiki very confusing sometimes. [For RealTime it says](http://wiki.garrysmod.com/page/Global/RealTime):

> You should use this function (or SysTime) for timing real-world events such as user interaction, **but not for timing game events such as animations**.

Does that include UI animations?
Then, [for CurTime it says](https://wiki.garrysmod.com/page/Global/CurTime):

> You should use this function for timing **in-game events** but not for real-world events.

Isn't a UI animation an in game event? Isn't everything an in game event? Or does this just mean things like moving around and shooting? If so, why not use SysTime as it's meant to be more accurate?

Then, [for RealTime it says](https://wiki.garrysmod.com/page/Global/RealTime):

> You should use this function (or SysTime) for timing real-world events such as user interaction, but **not for timing game events such as animations**.

Which one am I supposed to use for animations then? I guess it must be SysTime, but most of Garry's Mod seems to use CurTime for animations.

I just need some more straightforward examples of when to use each one. I've been using CurTime for derma animations and stuff like that so far, but I don't even know if I should use RealTime now

**Comment by Kefta** [comment]
Game events/animations is referring to actual entity behaviour and animations due to prediction. CurTime/UnPredictedCurTime should be used for managing entity effects so that they are properly scaled on every client smoothly. Since a UI event is a per-client event and completely dependant on their frame time, RealTime should be used.

I agree that the wiki isn't really clear on this -- I can add some examples later.

**Comment by MysteryPancake** [comment]
I still don't quite understand the difference. Could I just have an example for each (CurTime and RealTime)?

**Comment by Kefta** [comment]
Here's examples from GMod's base code. 
RealTime: https://github.com/Facepunch/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/cl_viewscreen.lua#L21
CurTime: https://github.com/Facepunch/garrysmod/blob/13490a8fdee47ff324cd11d57b5e0004d603c9e3/garrysmod/lua/weapons/weapon_fists.lua#L74

Again, CurTime should be used for anything in actual gameplay while RealTime should be used for anything HUD related, whether in a 2D or 3D context.

**Comment by MysteryPancake** [comment]
Wow, I didn't know GitHub did that sort of thing for resolves. I'm dumb
https://github.com/MysteryPancake/Rule-Book/commit/24f5b2f5674344e068f63e3b855b30c9a4493931
