### ISSUE TITLE
setmetatable

### ISSUE THREAD

**Issue by Mijyuoon** [MysteryPancake/GitHub-Rule-Book#2]
> setmetatable mustn't be used.

Why? Sometimes code that uses `setmetatable` would end up being a lot cleaner than one without. 

Metatables in Lua are used to implement OOP stuff like `obj:Func()`, which is useful when you want to make several things that must respond to a common interface. Not using metatables will result in a series of `if`/`else` statements, and that isn't exactly good.

Also OOP-like code in general can be cleaner by avoiding stuff like `mything.DoStuff(x)` in favor of `x:DoStuff()` and not polluting global namespace with tables for your functions.

**Comment by MysteryPancake** [comment]
ok

**Comment by MysteryPancake** [comment]
https://github.com/MysteryPancake/Rule-Book/commit/c994a23433c3a9d3b7a91b1b1158492aeeffad7a
