### ISSUE TITLE
for loops

### ISSUE THREAD

**Issue by Mijyuoon** [MysteryPancake/GitHub-Rule-Book#3]
> for loops must be used, not while, repeat, or until loops.

What about cases where you don't know the number of times you need to iterate because your loop exit condition is more complex? Like here:
```lua
while not self.Stack:IsEmpty() do
    local token = self.Stack:Pop()
    -- Do something with token
end
```

Or here:
```lua
local function parent_check(child, parent)
    while IsValid(parent) do
        if child == parent then
            return false
        end
        parent = parent:GetParent()
    end
    return true
end
```

**Comment by MysteryPancake** [comment]
I guess I do use them sometimes, but they just seem like they're waiting to crash the game. I'll remove that

**Comment by MysteryPancake** [comment]
https://github.com/MysteryPancake/Rule-Book/commit/e617f446fb5ff128563a877b5464153ec76a7fd1

**Comment by Kefta** [comment]
There's a lot of things in a programming language that can crash the game/program when used improperly -- it shouldn't deter you to use the feature, rather, it should promote you to be careful when doing so :)
