### ISSUE TITLE
IsValid

### ISSUE THREAD

**Issue by Kefta** [MysteryPancake/GitHub-Rule-Book#4]
IsValid(obj) is completely useless. If you are bouncing around nil and NULL in the same function, you need to refactor your code. Only obj:IsValid() should be used.

**Comment by Mijyuoon** [comment]
Well, sometimes `IsValid(x)` might make sense, like when `NULL` might unintentionally come from destroyed entities and your code uses `nil` to indicate absence of value (so it works in boolean context etc). Yeah, you can refactor that but code with `IsValid(x)` might look cleaner.

**Comment by Kefta** [comment]
It's extra checks. Type mixing nil and NULL shouldn't happen if you structure your entity code correctly.

**Comment by MysteryPancake** [comment]
ok
https://github.com/MysteryPancake/Rule-Book/commit/f65fb31fd98438a3683c7bd7fee39fda31cfc214

**Comment by Kefta** [comment]
I still stand by this. If you structure your code correctly, you never need global IsValid

**Comment by mentlerd** [comment]
That is only true if the code you write will be only used by you. `IsValid(obj)` prevents misuse of your code/public interface, and is a good tool for defensive programming.

I don't believe eliminating two nil checks is worth the hassle of going trough an entire codebase and replacing every `nil/missing` initialization with `NULL`, then keep arguing with people to not use nil.

**Comment by Kefta** [comment]
But you can't substitute nil for NULL in engine entity functions, and so you shouldn't allow it in your Lua functions. Although strict typing may be a preference for a weakly-typed language, extending C++ functions should follow their style for consistency to the programmer using them.

If you use global IsValid() on an entity, it does:
- 1 nil check on entity
- 2 __index calls for ent.IsValid
- 1 nil check on ent.IsValid
- 1 method call for ent.IsValid

Managing your member and function variables correctly can reduce that to 1 __index and 1 method call for ent.IsValid. From what I've seen in the default Garry's Mod codebase, 75% of the global IsValid calls could be replaced with var:IsValid(), and the extra 25% could be eliminated if panels were init'd differently.

**Comment by mentlerd** [comment]
I don't know of a single use case when you would want to explicitly pass a NULL entity to an engine function in the standard API.

While the standard `IsValid` implementation could really cache the result of `__index`, you are really blowing up the performance aspect on this one. Nil checks are actually cheaper than NULL checks.

The way I see is `IsValid` is the de-facto null check of garrysmod, that accounts for people passing both nil/NULL, therefore is more robust than the member version, for close to zero performance impact.

**Comment by Kefta** [comment]
But you are not just checking for nil, nor should you be type mixing. The performance save would only come in from someone passing nil explicitly, which like NULL, I don't see anyone doing. Where IsValid is used is with hooks that provide entities, and entity variables that are accessed over time, which at both times would NEVER be nil, thus is wasted performance.
