### ISSUE TITLE
math.randomseed

### ISSUE THREAD

**Issue by Kefta** [MysteryPancake/GitHub-Rule-Book#8]
There's nothing wrong with setting your own seed.. makes it less predictable.

**Comment by Mijyuoon** [comment]
Sometimes you actually *have to* use randomseed, like when you're making some procedurally generated shite and want to generate same things multiple times.

**Comment by MysteryPancake** [comment]
That's true I guess. The reason I wanted to avoid it is because it's a global sort of thing that affects all addons that might expect constantly random behaviour

**Comment by MysteryPancake** [comment]
https://github.com/MysteryPancake/Rule-Book/commit/1251e9344e4e376ea5cb880d166cdf5637e9d5c2

**Comment by Kefta** [comment]
Different seeds doesn't take away from the randomness, just the order. An addon should not rely on the seed to stay the same over time:  it should be set every time the sequence is needed again. If other addons really need to manage the random progression at all times, they can create their own random algorithm.
